CREATE TABLE ANSWERBOARD(
	BOARDNO NUMBER PRIMARY KEY,
	GROUPNO NUMBER NOT NULL,
	GROUPSQ NUMBER NOT NULL,
	TITLETAB NUMBER NOT NULL,
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	WRITER VARCHAR2(1000) NOT NULL,
	REGDATE DATE NOT NULL
);
-- 글 번호(PK)
CREATE SEQUENCE BOARDNOSQ NOCACHE;
-- 그룹 번호(새로운 글 등록할 때)
CREATE SEQUENCE GROUPNOSQ NOCACHE;


SELECT * FROM ANSWERBOARD ORDER BY GROUPNO DESC, GROUPSQ;

-- 첫번째 글 작성
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL, GROUPNOSQ.NEXTVAL, 1, 0, '첫번째 글', '1번 글 입니다.', '유저1', CURRENT_DATE); 

-- 두번째 글 작성
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL, GROUPNOSQ.NEXTVAL, 1, 0, '두번째 글', '2번 글 입니다.', '유저2', CURRENT_DATE); 

-- 1번글 답변 글 작성
-- 부모와 같은 GROUPNO
-- 부모의 GROUPSQ+1, 부모의 TITLETAB+2
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=1),
	(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=1)+1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=1)+2,
	'RE:첫번째 글','1글에 답글입니다.','유저2',CURRENT_DATE 
);

SELECT * FROM ANSWERBOARD
ORDER BY GROUPNO DESC, GROUPSQ;

-- 세번째 글 작성
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL, GROUPNOSQ.NEXTVAL, 1, 0,'세번째 글','3번 글 입니다.','유저3',CURRENT_DATE);

-- 2번 글에 답변글 작성
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=2),
	(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=2)+1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=2)+2,
	'RE:두번째 글','2번글에 답글입니다.','유저1',CURRENT_DATE 
);

-- 답변글 작성(RE:두번째 글, BOARDNO=5)
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=5),
	(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=5)+1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=5)+2,
	'RE:RE:두번째 글','2번글 답변글에 답변글','유저1',CURRENT_DATE 
);

SELECT * FROM ANSWERBOARD
ORDER BY GROUPNO DESC, GROUPSQ;

-- 답변글 작성(두번쨰 글, BOARDNO=2)

-- 부모와 같은 GROUPNO에서
-- 부모의 GROUPSQ보다 큰 글들의 GROUPSQ+1
UPDATE ANSWERBOARD SET GROUPSQ = GROUPSQ+1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=2)
	AND GROUPSQ>(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=2);

-- 부모와 같은 GROUPNO,
-- 부모의 GROUPSQ+1, 부모의 TITLETAB+2
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=2),
	(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=2)+1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=2)+2,
	'RE:두번째 글에 답변글.','2번글 답변글!','유저2',CURRENT_DATE 
);


-- 답변 작성(RE:두번째 글, BOARDNO=7)
-- 1. UPDATE
UPDATE ANSWERBOARD SET GROUPSQ = GROUPSQ+1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=7)
	AND GROUPSQ>(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=7);
-- 2. INSERT
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=7),
	(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=7)+1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=7)+2,
	'RE:RE:두번째 글','2번글 답변에 답글!!!','유저3',CURRENT_DATE 
);