CREATE TABLE MYMEMBER(
	MYNO NUMBER PRIMARY KEY,
	MYID VARCHAR2(500) NOT NULL UNIQUE,
	MYPW VARCHAR2(500) NOT NULL,
	MYNAME VARCHAR2(300) NOT NULL,
	MYADDR VARCHAR2(4000) NOT NULL,
	MYPHONE VARCHAR2(20) NOT NULL UNIQUE,
	MYEMAIL VARCHAR2(100) NOT NULL UNIQUE,
	MYENABLED VARCHAR2(2) NOT NULL CHECK(MYENABLED IN ('Y','N')),
	MYROLE VARCHAR2(50) NOT NULL
);
CREATE SEQUENCE SEQ_MYMEMBER
NOCACHE;

INSERT INTO MYMEMBER
VALUES(SEQ_MYMEMBER.NEXTVAL,'ADMIN','1234','관리자','관리시 관리구 관리동','010-1234-5678','ADMIN@MYMEMBER.COM','Y','ADMIN');

SELECT * FROM MYMEMBER;